language: python

python:
  - 3.5
  - 3.6

# install dependencies
before_install:
  - python --version
  - apt-get install python3-gi libappindicator3-dev gnome-icon-theme

script:
  - python3 -m py_compile *.py
