dist: bionic

language: python

python:
  - 3.6
  - 3.7
  - 3.8

# install dependencies
before_install:
  - python --version
  - sudo apt-get install python3-gi libappindicator3-dev gnome-icon-theme

script:
  - python3 -m py_compile *.py
